accounts/urls.py
from django.urls import path
from .views import *
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('edit/<int:pk>/', views.edit_user, name='edit_user'),
    path('', views.account_info, name='account_info'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:pk>', views.product_detail, name='product_detail'),
    path('like/<int:pk>', views.like, name='like'),
    
    path('cart/', views.cart_list, name='cart_list'),
    path('<int:pk>/add/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:pk>', views.delete_from_cart, name = 'delete_from_cart'),
    path('accept/<int:pk>', views.accept, name='accept'),

    path('about/', views.about, name='about'),
    path('done/', views.done_purchases, name='done_purchases'),
    path('<str:product_type>', views.product_list, name='product_type'),

    path('custom_create/', views.custom_create, name='custom_create'),
    path('custom/<int:pk>', views.custom_purchase_detail, name='custom_detail'),
    path('custom/delete/<int:pk>', views.delete_custom_purchase, name='custom_delete'),
    path('custom_accept/<int:pk>', views.custom_accept, name='custom_accept'),

    # path('custom/edit/<int:pk>', views.custom_edit, name='custom_edit'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_roor = settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from mysite import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

class Product(models.Model):
    TYPE_CHOISES = (
        ('badge', "Значок"),
        ('earring', "Серьги"),
        ('necklace', "Кулон"),
    )
    name = models.CharField(max_length=255)
    product_type = models.CharField(max_length=10, choices=TYPE_CHOISES)
    description = models.TextField(null=True, blank=True)
    price = models.PositiveIntegerField()
    image = models.ImageField(upload_to='static/images', blank=True)
    # likes = models.IntegerField(default=0)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes', blank=True)
    likes_number = models.IntegerField(default=0)
    # status = models.CharField(max_length=10, choices=STATUS_CHOISES, null=True, blank=True)
    # clients = models.ManyToManyField(settings.AUTH_USER_MODEL, null=True, blank=True)
    # rate = models.PositiveIntegerField(null=True, blank=True)
    # cart = PublishedManager()
    objects = models.Manager()

    class Meta:
        ordering = ('-price',)
        
    def __str__(self):
        return self.name



class Purchase(models.Model):
    STATUS_CHOISES = (
        ("awaiting", 'В обработке'),
        ('confirmed', 'Подтвержден'),
        ('done', 'Готов'),
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOISES, default='awaiting')
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='basket', on_delete='CASCADE')
    product = models.ForeignKey(Product, related_name='+', on_delete='CASCADE')
    date = models.DateTimeField(auto_now_add=True)
    count = models.PositiveSmallIntegerField(verbose_name='Количество')

    @property
    def cost(self):
        return self.product.price * self.count


class CustomPurchase(models.Model):
    STATUS_CHOISES = (
        ("awaiting", 'В обработке'),
        ('confirmed', 'Подтвержден'),
        ('done', 'Готов'),
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOISES, default='awaiting', blank=True, null=True)
    image1 = models.ImageField(upload_to='static/images', verbose_name='Изображение 1', blank=True, default='no-image.jpg')
    image2 = models.ImageField(upload_to='static/images', blank=True, verbose_name='Изображение 2', default='no-image.jpg')
    image3 = models.ImageField(upload_to='static/images', blank=True, verbose_name='Изображение 3', default='no-image.jpg')
    description = models.TextField(verbose_name='Описание')
    size = models.PositiveIntegerField(verbose_name='Размер')
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete='CASCADE')


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    email = models.EmailField()
    body = models.TextField(verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'comment by {} on {}'.format(self.name, self.product)

shop/forms.py
from django import forms
from .models import Comment, Purchase, CustomPurchase

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('email', 'body')

class CartCreationForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ('count',)

class CustomPurchaseForm(forms.ModelForm):
    class Meta:
        model = CustomPurchase
        fields = ('image1', 'image2', 'image3', 'size', 'description')

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Purchase, Comment, CustomPurchase
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm, CartCreationForm, CustomPurchaseForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.views.generic import TemplateView
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect

def product_list(request, product_type=None):
    if product_type==None:
        object_list = Product.objects.all().order_by('-likes_number')
    else:
        object_list = Product.objects.filter(product_type=product_type).order_by('-likes_number')
    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    
    return render(request, 'list.html', {'page': page, 
                                        'products': products})


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    
    is_liked = False
    if product.likes.filter(id=request.user.id).exists():
        is_liked = True

    comments = product.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.product = product
            new_comment.name = request.user
            new_comment.save()
            comment_form=CommentForm()
    else:
        comment_form = CommentForm()
    return render(request, 'product_detail.html', {'product': product,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form
                                           })
@login_required
def custom_purchase_detail(request, pk):
    custom_purchase = get_object_or_404(CustomPurchase, pk=pk)
    images = [custom_purchase.image1, custom_purchase.image2, custom_purchase.image3]

    while 'no-image.jpg' in images:
        images.remove('no-image.jpg')
    if bool(images)==False:
        images = [custom_purchase.image1,]
    return render(request, 'custom_purchase_detail.html', {'custom_purchase': custom_purchase,
                                                            'images':images})

@login_required
def cart_list(request):
    carts = Purchase.objects.filter(Q(customer=request.user, status='awaiting')|Q(customer=request.user, status='confirmed')).order_by('status')
    total = 0
    custom = CustomPurchase.objects.filter(customer=request.user)
    is_empty = bool(carts)
    is_anycustom = bool(custom)
    for i in carts:
        total += i.cost
    return render(request, 'cart.html', {'carts': carts,
                                        'total':total,
                                        'is_empty':is_empty,
                                        'custom':custom,
                                        'is_anycustom':is_anycustom})

def about(request):
    return render(request, 'index.html')

def upload(request):
    if request.method == 'POST':
        uploaded_file= request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        url = fs.url(name)
    return render(request, 'upload.html', locals())

@login_required
def custom_create(request):
    if request.method == 'POST':
        form = CustomPurchaseForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            new_cart = form.save(commit=False)
            print(new_cart)
            new_cart.customer = request.user
            new_cart.save()
            messages.success(request, 'It has successfully added')
            return redirect('shop:custom_detail', new_cart.pk)
    else:
        form = CustomPurchaseForm(data=request.GET)
    return render(request, 'create_custom.html', {'form':form})

@login_required
def custom_edit(request, pk):
    cp = get_object_or_404(CustomPurchase, pk=pk)
    if request.method=='POST':
        form = CustomPurchaseForm(request.POST, instance=cp)
        if form.is_valid():
            cp=form.save(commit=False)   
            cp.save()
            return redirect('shop:custom_detail', pk)
    else:
        form = CustomPurchaseForm(request.POST, instance=cp)
    return render(request, 'edit_custom.html', {'form':form})

@login_required
def add_to_cart(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = CartCreationForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_cart = form.save(commit=False)
            new_cart.customer = request.user
            new_cart.product = product
            new_cart.save()
            return redirect('shop:product_list')
    else:
        form = CartCreationForm(data=request.GET)
    return render(request, 'add_to_cart.html', {'form':form})

@login_required
def delete_custom_purchase(request, pk):
    purchase = CustomPurchase.objects.get(pk=pk)
    if purchase.status=='awaiting':
        purchase.delete()
        return redirect('shop:cart_list')
    return render(request, 'error_page.html')

@login_required
def delete_from_cart(request, pk):
    purchase = Purchase.objects.get(pk=pk)
    if purchase.status=='awaiting':
        purchase.delete()
        return redirect('shop:cart_list')
    return render(request, 'error_page.html')

@login_required
def done_purchases(request):
    done = Purchase.objects.filter(customer=request.user, status='done')
    return render(request, 'done_purchases.html', {'done': done})

@login_required
def like(request, pk):
    product = get_object_or_404(Product, pk=pk)
    is_liked = False
    if product.likes.filter(id=request.user.id).exists():
        product.likes.remove(request.user)
        product.likes_number-=1
        product.save()
        is_liked = False
    else:
        product.likes.add(request.user)
        product.likes_number+=1
        product.save()
        is_liked = True
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def accept(request, pk):
    purchase = get_object_or_404(Purchase, pk=pk)
    purchase.status='confirmed'
    purchase.save()
    return redirect('shop:cart_list')

@login_required
def custom_accept(request, pk):
    purchase = get_object_or_404(CustomPurchase, pk=pk)
    purchase.status='confirmed'
    purchase.save()
    return redirect('shop:cart_list')

shop/templates/add_to_cart.html
{%extends 'base.html'%}
{%block content%}
  <h2>Сколько шт вы хотите приобрести?</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить в корзину">
    </form>
{%endblock%}

shop/templates/base.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {%block title%}{%endblock%}
<!--
Neaty HTML Template
http://www.templatemo.com/tm-501-neaty
-->
    <!-- load stylesheets -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">                                     
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">                                
    <link rel="stylesheet" href="{% static 'css/style.css' %}">                                    
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}"/>
    <!-- <link rel="stylesheet" href="../static/css/rating.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
</head>
<body> 
    <div class="container">
            <div class="row">
                <div class="tm-left-right-container">
                    <!-- Left column: logo and menu -->
                    <div class="tm-blue-bg tm-left-column">                        
                        <div class="tm-logo-div text-xs-center">
                            <a href='{% url "shop:product_list" %}'><img src="{% static 'images/tm-neaty-logo.png'%}" height="100" alt="Logo">
                            <h1 class="tm-site-name">aVc</h1></a>
                        </div>
                        <nav class="tm-main-nav">
                            <ul class="tm-main-nav-ul">
                                <li class="tm-nav-item">
                                    <a href="{% url 'shop:about'%}" class="tm-nav-item-link">О нас</a>
                                </li>
                                <li class="tm-nav-item">
                                    <a href="{% url 'shop:product_list' %}" class="tm-nav-item-link">Каталог</a>
                                </li>
                                <li class="tm-nav-item">
                                    <a href="{% url 'shop:cart_list' %}" class="tm-nav-item-link">Корзина</a>
                                </li>
                                <!-- <li class="tm-nav-item">
                                    <a href="{% url 'shop:custom_create' %}" class="tm-nav-item-link">Create</a>
                                </li> -->
                                <br>
                                {% if user.is_authenticated %}
                                <li class="tm-nav-item">
                                    <a href="{{user.get_absolute_profile_url}}">Привет, {{user.username}}</a></li>
                                <li class="tm-nav-item">   
                                    <a href ="{% url 'logout' %}">Выйти</a>
                                </li>
                                
                                {% else %}
                                <li class="tm-nav-item">
                                    <a href="{% url 'login' %}">Войти</a></li>
                                <li class="tm-nav-item">
                                    <a href= "{% url 'accounts:signup' %}">Регистрация</a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>                                         
                    </div> <!-- Left column: logo and menu -->
                    
                    <!-- Right column: content -->
                    <div class="tm-right-column">
                        <figure>
                            {%block figure%}{%endblock%}
                        </figure>

                        <div class="tm-content-div">
                            <!-- Welcome section -->
                            

                            <!-- Gallery One section -->     
                            {%block section%} {%endblock%}
                            <section id="welcome" class="tm-section">
                                {%block content%}{%endblock%}
                            </section>
                            

                            

                            <!-- Contact Us section -->
                            <section id="contact" class="tm-section">
                                <header><h2 class="tm-blue-text tm-section-title tm-margin-b-30">Как с нами связаться</h2></header>

                                <div class="row">
                                    <div class="col-lg-6">
                                       <a href="https://www.instagram.com/avc.kg/" target="_parent">
                                           <img src="{% static 'images/inst.png'%}" alt="Image" width="60"> inst/aVc.kg </a>
                                    </div>
                                    
                                    <div class="col-lg-6 tm-contact-right">
                                        <p>
                                         <img src="{% static 'images/whatsapp.png'%}" alt="Image" width="60"> +996 556 01 87 22  
                                        </p>
                                    </div>
                                </div>
                                
                            </section>
                            <footer>
                                <p class="tm-copyright-p">&copy; <span class="tm-current-year">2020</span> aVc.kg
                                
                                </p>
                            </footer>
                        </div>  
                        
                    </div> <!-- Right column: content -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
                            
</body>
</html>

shop/templates/cart.html
{%extends 'base.html'%}
{%block content%}
<h2 class='history' >
    <a href="{% url 'shop:custom_create' %}" class="tm-nav-item-link" style="color:#658E08;">Создать свой заказ</a>  |                         
    <a href="{% url 'shop:done_purchases' %}" style="color:#658E08;">История заказов</a>
</h2>
<br><br><br><br>
    {%for purchase in carts%}
        <h2><a href="{% url 'shop:product_detail' purchase.product.pk%}" style="color:#658E08;">{{ purchase.product }} </a> {{purchase.count}} шт.</h2>
        <img src='../../media/{{purchase.product.image}}' class="list-item-img" width="250" height="200"></a>
        <p>{{purchase.cost}} сом</p>
        <p>Статус заказа: <b>{{ purchase.get_status_display }}</b></p>
        <p>
            <a href="{% url 'shop:accept' purchase.pk%}"><input type="button" value="Подтвердить"></a>
            <a href="{% url 'shop:delete_from_cart' purchase.pk%}"><input type="button" value="Удалить"></a>
        </p>
        <br><br>
    {%endfor%}
    {% if is_anycustom %}
        <h2>Специальные заказы</h2>
    {%endif%}
    {%for purchase in custom%}
        <a href="{% url 'shop:custom_detail' purchase.pk%}"><img src='../../media/{{purchase.image1}}' class="list-item-img" width="180" height="180"></a>
        <p>{{purchase.description}}</p>
        <p>Размер: {{ purchase.size}} см</p>
        <p>Статус заказа: <b>{{ purchase.get_status_display }}</b></p>
        <a href="{% url 'shop:custom_delete' purchase.pk%}"><input type="button" value="Удалить"></a>
        <a href="{% url 'shop:custom_accept' purchase.pk%}"><input type="button" value="Подтвердить"></a>
        <br><br>
    {%endfor%}
    {% if is_empty %}
        <h2>Итого: {{total}} сом</p>   
    {% else %}
        <h2>Корзина пуста</p>
    {%endif%}
    <br><br>
{%endblock%}

shop/templates/create_custom.html
{%extends 'base.html'%}
{% load crispy_forms_tags %}
{%block content%}
  <h2>Создать свой заказ</h2>
    <form method="POST" enctype="multipart/form-data">
 
        {{form.description|as_crispy_field }}   
        Размер* {{ form.size}} см
        <p><b>Обязательное поле</b></p>
        <br>
        <p>Загрузите фото при желании (до 3)</p>
        {% csrf_token %}
        {{ form.image1|as_crispy_field  }}
        {{ form.image2|as_crispy_field  }}
        {{ form.image3|as_crispy_field  }}
        <br><br>
        <button type="submit">Создать</button>
    </form>
{%endblock%}

shop/templates/custom_purchase_detail.html
{%extends 'base.html'%}
{%block section%}
{% for img in images %}
<img src='../../media/{{img}}' width="200"></a>
{%endfor%}
    <p>Описание: {{custom_purchase.description}}</p>
    <p>Размер: {{custom_purchase.size}} см</p> 
    <p>Цена: договорная</p>
    <a href="{% url 'shop:custom_accept' custom_purchase.pk%}"><input type="button" value="Подтвердить"></a>
    <a href="{% url 'shop:custom_delete' custom_purchase.pk%}"><input type="button" value="Удалить"></a>
{%endblock%}

shop/templates/done_purchases.html
{%extends 'base.html'%}
{%block content%}
    {%for purchase in done%}
        <h2 class="tm-blue-text tm-section-title tm-margin-b-30"><a href="{% url 'shop:product_detail' purchase.product.pk%}">{{ purchase.product }}</a>  {{purchase.count}} шт.</h2>
        <img src='../../media/{{purchase.product.image}}' class="list-item-img" width="250" height="200"></a>
        <p>{{purchase.cost}} сом</p>
        <br><br>
    {%endfor%}


{%endblock%}

shop/templates/edit_custom.html
{%extends 'base.html'%}
{% load crispy_forms_tags %}
{%block content%}
    <form method="POST" enctype="multipart/form-data">
 
        {{form.description|as_crispy_field }}   
        Размер* {{ form.size}} см
        <p><b>Обязательное поле</b></p>
        <br>
        <p>Загрузите фото при желании (до 3)</p>
        {% csrf_token %}
        {{ form.image1|as_crispy_field  }}
        {{ form.image2|as_crispy_field  }}
        {{ form.image3|as_crispy_field  }}
        <br><br>
        <button type="submit">Создать</button>
    </form>
{%endblock%} 

shop/templates/error_page.html
{%extends 'base.html'%}
{%block content%}
    <h3>Вы не можете удалить подтвержденный заказ!</h3><br>
    <p>Если у вас возникли какие проблемы с заказами, то пишите нам в WhatsApp</p>
{%endblock%}

shop/templates/index.html
{%extends 'base.html'%}
{%load static%}

{%block figure%}
    <img src="{% static 'images/1.jpg'%}" alt="Header image" class="img-fluid">    
{%endblock%}

{%block section%}
<section id="welcome" class="tm-section"></section>
    <header>
        <h2 class="tm-blue-text tm-welcome-title tm-margin-b-45">Добро пожаловать в aVc</h2>
    </header>
    <p>Рады приветсовать Вас в aVc - хэндмейд мире полимерной глины. Здесь Вы можете ознакомиться с товаром, который мы Вам предлагаем: сережки, кулоны и значки. 
    И все из полимерной глины! 
    </p>
    <p>Полимерная глина – это специально созданный материал, который лепится как пластилин, но при этом затвердевает в духовке при очень высоких температурах.
Из такого материала можно создавать все что угодно, начиная от скульптур и заканчивая миниатюрами.</p>
</section>
<!-- About section -->
<section id="about" class="tm-section">
    <div class="row">                                                                
        <div class="col-lg-8 col-md-7 col-sm-12 col-xs-12 push-lg-4 push-md-5">
            <header>
                <h2 class="tm-blue-text tm-section-title tm-margin-b-45">О нас</h2>
            </header>
            <p>Давайте знакомиться! Мы сестры и занимаемся лепкой из полимерной глины с 2016 года по сей день.</p>
            <p>Меня зовут Асель. Мне 20 лет. Я учусь на программиста в Кыргызско-Германском Институте прикладной информатики (INAI). Но при этом люблю заниматься творчеством, подобным этому.</p>
            <p>Я Салкын, мне 16 лет. С детсва любила создавать что-то интересное. Так сюда меня и занесло. Поэтому поступила учиться на дизайнера, чтобы на полном серьезе связать свою судьбу с творчеством.</p> 
        </div>

        <div class="col-lg-3 col-md-5 col-sm-12 col-xs-12 pull-lg-8 pull-md-7 tm-about-img-container">
            <img src="{% static 'images/2.jpg'%}" alt="Image" class="img-fluid">
        </div>  
    </div>                            
</section>  

{%endblock%}

shop/templates/list.html
{%extends 'base.html'%}
{%block section%}

    <div class="filter">
        <h3><a  href='{% url "shop:product_list" %}' style="color:#658E08;">Все</a></h3>
        <h3><a  href='{% url "shop:product_type" "earring" %}' style="color:#658E08;">Серьги</a></h3>
        <h3><a href='{% url "shop:product_type" "necklace" %}' style="color:#658E08;">Кулоны</a></h3>
        <h3><a href='{% url "shop:product_type" "badge" %}' style="color:#658E08;">Значки</a></h3>
    </div>
    <section id="secondgallery" class="tm-section">
        <header><h2 class="tm-blue-text tm-section-title tm-margin-b-30"></h2></header>
        <div class="secondgallery-list tm-gallery-container tm-gallery-1">
    {%for product in products%}
        
        <div class="list-item tm-img-container-1" >
            <a href="{% url 'shop:product_detail' product.pk%}">
            <img src='../../media/{{product.image}}' class="list-item-img img-fluid tm-img-tn" width="250" height="200"></a>
            <p> <a href="{%url 'shop:like' product.pk %}" style="color:#658E08;"><p><i onclick="myFunction(this)" class="fa fa-thumbs-up"></i></a> {{product.likes_number}}
          
        </div>
       
    {%endfor%}
    </div>
    </section>
    <section>
    {% include 'pagination.html' with page=products %}
    </section>
{%endblock%}

shop/templates/pagination.html
<div class='pagination'>
    <span class='step-links'>
        {% if page.has_previous %}
        <a href="?page=1" style='color: #004d00;'>&laquo;Начало</a>
            <a href='?page={{ page.previous_page_number }}' style='color: #004d00;'>Назад </a>
        {% endif %}
    <span class='current'>
        Страница {{ page.number }} из {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
        <a href='?page={{ page.next_page_number }}' style='color: #004d00;'>Вперед  </a>
        <a href='?page={{ page.paginator.num_pages }}' style='color: #004d00;'>  Конец &raquo;</a>
    {% endif %}
    </span>
</div>

shop/templates/product_detail.html
{%extends 'base.html'%}
{%block section%}

<h1>{{ product.name }}</h1>
<img src='../../media/{{product.image}}' width="200" height="140"></a>
    <p>{{product.description}}</p>
    <p>{{product.price}} сом</p> 
    
    <a style="color:#658E08;" href="{%url 'shop:like' product.pk %}"><p><i onclick="myFunction(this)" class="fa fa-thumbs-up"></i></a> {{product.likes_number}}</p>
    <!-- <a href="{%url 'shop:like' product.pk  %}"><p><i onclick="myFunction(this)" class="fa fa-thumbs-down"></i></a> </p> -->
  
<section class="tm-section">
    <a href="{% url 'shop:add_to_cart' product.pk%}"><input type="button" value="Добавить в корзину"></a>
</section>

    <section class="tm-section">
    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} комментариев </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class='comment'>
            <p class='info'>
                {{ comment.name }}
                {{ comment.created }}:
            </p>
        {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>Нет комментариев</p>
    {% endfor %}
    
        <h2>Добавить новый комментарий</h2>
        <form method='post'>
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type='submit' value='Добавить'></p>
        </form>
    </section>
{%endblock%}

shop/templates/rating.html
<html>

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="../static/css/rating.css">
  <title>Star rating using pure CSS</title>
</head>

<body>
  <div class="rate">
    <input type="radio" id="star5" name="rate" value="5" />
    <label for="star5" title="5">5 stars</label>
    <input type="radio" id="star4" name="rate" value="4" />
    <label for="star4" title="4">4 stars</label>
    <input type="radio" id="star3" name="rate" value="3" />
    <label for="star3" title="3">3 stars</label>
    <input type="radio" id="star2" name="rate" value="2" />
    <label for="star2" title="2">2 stars</label>
    <input type="radio" id="star1" name="rate" value="1" />
    <label for="star1" title="1">1 star</label>
  </div>

    <script src="./js/main.js"></script>
</body>

</html>

shop/templates/upload.html
{% block content %}
    <h2>Upload</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="document">
        <button type="submit">Upload file</button>
    </form>
    {% if url %}
        <p>Uploaded file:<a href="product_images">{{ media }}</a></p>
    {% endif %}
{% endblock %}